#!/bin/bash

source ./.env

# Create testing container
docker run -d -p 50000:80 -it --name Test $IMAGE:$TAG

# Test the container outside itself by each command
docker exec -it Test cat /etc/os-release | grep VERSION=
docker exec -it Test git version
docker exec -it Test vim --version | grep 'Included patches'
docker exec -it Test nano -V | grep 'GNU nano, version'

# Delete the testing containter finally
docker stop Test; docker rm Test
